services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - unsplash_image_app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/unsplash
    ports:
      - "3001:3001"
    networks:
      - unsplash_image_app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - unsplash_image_app-network

volumes:
  mongodb_data:

networks:
  unsplash_image_app-network:
    driver: bridge